<?php

/**
 * PluginsfDoctrinePayzenPayment_2_8
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfDoctrinePayzenPlugin
 * @subpackage model
 * @author     Patrick Dos Santos <patrick.dos-santos [at] solution-interactive.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfDoctrinePayzenPayment_2_8 extends BasesfDoctrinePayzenPayment_2_8
{

}