<?php

/**
 * PluginsfDoctrinePayzenTransIdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfDoctrinePayzenTransIdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginsfDoctrinePayzenTransIdTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfDoctrinePayzenTransId');
    }
    
    /**
     * Fetches the vads_trans_id from the database
     * @return sfDoctrinePayzenTransId The vads_trans_id from the database 
     */
    public static function getSfDoctrinePayzenTransId()
    {
        return self::getInstance()->createQuery()->fetchOne();
    }
}