<?php

/**
 * PluginsfDoctrinePayzenTransId
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfDoctrinePayzenPlugin
 * @subpackage model
 * @author     Patrick Dos Santos <patrick.dos-santos [at] solution-interactive.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfDoctrinePayzenTransId extends BasesfDoctrinePayzenTransId
{

    public function getTransId()
    {
        $this->updateTransId();
        $transId = $this->getCurrentId();
        $this->setCurrentId($transId + 1);
        $this->save();
        return $transId;
    }
    
    public function updateTransId()
    {
        $now = date('Y-m-d');
        if (substr($this->getLastReset(), 0, 10) !== $now)
        {
          $this->setCurrentId(1);
          $this->setLastReset($now);
        }
    }
}