<?php

/**
 * PluginsfDoctrinePayzenPayment_2_8Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfDoctrinePayzenPayment_2_8Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginsfDoctrinePayzenPayment_2_8Table The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfDoctrinePayzenPayment_2_8');
    }
}