sfDoctrinePayzenPayment_2_8:
  actAs: [Timestampable]
  columns:
    #payzen payment
    signature:                      {type: clob, notnull: true}
    vads_action_mode:               {type: string(255), notnull: true}
    vads_amount:                    {type: int(12), notnull: true}
    vads_available_languages:       {type: string(255)}
    vads_capture_delay:             {type: string(3)}
    vads_contracts:                 {type: clob}
    vads_contrib:                   {type: string(255)}
    vads_ctx_mode:                  {type: string(255), notnull: true}
    vads_currency:                  {type: string(3), notnull: true}
    vads_cust_address:              {type: string(255)}
    vads_cust_cell_phone:           {type: string(255)}
    vads_cust_city:                 {type: string(255)}
    vads_cust_country:              {type: string(2)}
    vads_cust_email:                {type: string(127)}
    vads_cust_id:                   {type: string(63)}
    vads_cust_name:                 {type: string(127)}
    vads_cust_phone:                {type: string(32)}
    vads_cust_title:                {type: string(63)}
    vads_cust_zip:                  {type: string(63)}
    vads_language:                  {type: string(2)}
    vads_order_id:                  {type: string(12)}
    vads_order_info:                {type: string(255)}
    vads_order_info_2:              {type: string(255)}
    vads_order_info_3:              {type: string(255)}
    vads_page_action:               {type: string(255), notnull: true}
    vads_payment_cards:             {type: string(127)}
    vads_payment_config:            {type: string(255), notnull: true}
    vads_redirect_error_message:    {type: string(255)}
    vads_redirect_error_timeout:    {type: string(255)}
    vads_redirect_success_message:  {type: string(255)}
    vads_redirect_success_timeout:  {type: string(255)}
    vads_return_mode:               {type: string(255), notnull: true}
    vads_ship_to_city:              {type: string(255)}
    vads_ship_to_country:           {type: string(255)}
    vads_ship_to_name:              {type: string(255)}
    vads_ship_to_phone_num:         {type: string(255)}
    vads_ship_state:                {type: string(255)}
    vads_ship_street:               {type: string(255)}
    vads_ship_street2:              {type: string(255)}
    vads_ship_to_zip:               {type: string(255)}
    vads_shop_name:                 {type: string(255)}
    vads_shop_url:                  {type: string(255)}
    vads_site_id:                   {type: string(8), notnull: true}
    vads_theme_config:              {type: string(255)}
    vads_trans_date:                {type: string(14), notnull: true}
    vads_trans_id:                  {type: string(6), notnull: true}
    vads_validation_mode:           {type: string(1)}
    vads_version:                   {type: string(255), notnull: true}
    vads_url_cancel:                {type: clob}
    vads_url_error:                 {type: clob}
    vads_url_referral:              {type: clob}
    vads_url_refused:               {type: clob}
    vads_url_return:                {type: clob}
    vads_url_success:               {type: clob}
    vads_user_info:                 {type: clob}
    #payzen return
    vads_auth_result:               {type: string(2), notnull: true}
    vads_auth_mode:                 {type: string(255), notnull: true}
    vads_auth_number:               {type: string(6), notnull: true}
    vads_card_brand:                {type: string(127), notnull: true}
    vads_card_number:               {type: string(19), notnull: true}
    vads_extra_result:              {type: string(2), notnull: true}
    vads_warranty_result:           {type: string(255), notnull: true}
    vads_payment_certificate:       {type: string(40), notnull: true}
    vads_result:                    {type: string(255), notnull: true}
    vads_payment_src:               {type: string(255)}
    vads_contract_used:             {type: string(250)}
    vads_expiry_month:              {type: string(2)}
    vads_expiry_year:               {type: string(4)}
    vads_threeds_enrolled:          {type: string(1)}
    vads_threeds_cavv:              {type: string(28)}
    vads_threeds_eci:               {type: string(2)}
    vads_threeds_xid:               {type: string(28)}
    vads_threeds_cavvAlgorithm:     {type: string(1)}
    vads_threeds_status:            {type: string(1)}
    vads_threeds_sign_valid:        {type: string(1)}
    #sfDoctrinePayzenPlugin
    
sfDoctrinePayzenTransId:
  columns:
    current_id: {type: integer, default: 1}
    last_reset: {type: datetime}